### ISSUE TITLE
.slice() doesn't work when copying wave to output

### ISSUE THREAD

**Issue by aatishb** [GoogleChromeLabs/web-audio-samples#153]
Hi, I'm not sure if this is a bug or just a javascript thing that's throwing me off. Here is my issue when using a worklet:

```
class AudioProcessor extends AudioWorkletProcessor {

  constructor(options) {
    super(options);
  }

  process(inputs, outputs, parameters) {
    let input = inputs[0][0];
    let output = outputs[0][0];
    let numSamples = output.length;

    let myWave = new Float32Array(numSamples);

    for (let i = 0; i < numSamples; i++) {
      myWave[i] = (2 * Math.random() - 1) * 0.1;
    }
    
    // this works
    for (let i = 0; i < numSamples; i++) {
      output[i] = myWave[i];
    }

    // but this doesn't
    // output = myWave.slice();
    
    // and this doesn't too
    // output = myWave
    
    return true;
  }
}

registerProcessor('audio-processor', AudioProcessor);

```
Live test [here](https://glitch.com/edit/#!/indigo-ptarmigan).

Is it necessary for me to iterate through myWave with a for loop to pipe it to output? Why doesn't .slice or just assigning output to myWave work?

Thanks.

**Comment by hoch** [comment]
`output.set(myWave)` would be the fastest one. (equivalent of memcpy)

`output` reference is prepared by the system and you can't replace it in the current implementation. The memory allocation in the audio callback must be kept minimum. This is because any allocation will eventually lead to garbage collection (thus glitches in the audio stream):

1. `.slice` returns a new Array object which will end up with garbage.
3. `new Float32Array()` also creates a new TypedArray. It generates garbage.

Also the `outputs` slot is prepared by the system, the container object should not be replaced. The user code is supposed to touch the content inside.

Does it make sense?

**Comment by aatishb** [comment]
@hoch thanks, this is very helpful. So if I want to use an array to store & process sound data before setting it to output, I should maybe create a global array that is updated on each frame / process loop?

**Comment by hoch** [comment]
Yes, I would recommend that.

**Comment by aatishb** [comment]
Thanks!
