### ISSUE TITLE
All of the samples using audio worklet are garbled/glitching on Chrome for Android across multiple devices

### ISSUE THREAD

**Issue by svenoaks** [GoogleChromeLabs/web-audio-samples#189]

**Comment by JamesGreenaway** [comment]
my ipad won't even load the page and even on my pixelbook the examples glitch.

**Comment by rtoy** [comment]
Chrome on iOS uses webkit which doesn't have AudioWorklet support.  This also means Safari doesn't have AudioWorklet support either.

These issues reported here are bugs in Chrome, not with the demos.

**Comment by JamesGreenaway** [comment]
I am aware of audioworklet compatibility, however on iOS, the whole site doesn't even load when visiting, and when I do visit it on desktop chrome the performance is poor. Are you saying this is Chromes fault? I was under the impression that audioworklets would help to avoid performance issues. When I run the examples on desktop Chrome (78) I receive lots of glitches an dropouts. Doesn't seem like this is the intended impression. Either way, it's not the best representation of what I'd hoped GoogleChromeLabs would showcase.

**Comment by rtoy** [comment]
Oh, don't know about the iOS issue since I don't have an iOS device.

The dropouts/glitches are due Chrome; there are several bugs filed about this and they're mostly because worklets don't run at real-time priority unless you enable that in chrome://flags and even there there are bugs in that because you don't always get real-time priority.  They are being worked on.  The demos work reasonably well with Chrome on MacOS.

I think the demos are fine; it's the browser that isn't right now.

**Comment by hoch** [comment]
The thread problem significantly depends on the platform/OS. Please report your platform/OS via crbug.com:
https://bugs.chromium.org/p/chromium/issues/detail?id=1006844

**Comment by scottstensland** [comment]
this demo repo needs some attention ... none of the demos work on linux or android sometime due to file relative layout issues as in index.html cannot find its underlying xxx.js files  

for example cd into dir

    ~/src/github.com/GoogleChromeLabs/web-audio-samples/audio-worklet

and spin up a server to render that dir and point any browser [ chrome Version 83.0.4100.3 (Official Build) dev (64-bit)]   there to see browser console messages like

```
0.0.0.0/:32 GET http://0.0.0.0:8000/shared-buffer-worklet-node.js net::ERR_ABORTED 404 (File not found)
```

with these html issues demos all fail to execute looks to be due to a reorg of files not fully baked

**Comment by hoch** [comment]
Spin up the server at `GoogleChromeLabs/web-audio-samples` instead of `audio-worklet` directory. The browser is trying to find files based on a wrong root.

That's a simple path problem and it has nothing to do with a glitching issue.

**Comment by hoch** [comment]
As pointed out the [above](https://github.com/GoogleChromeLabs/web-audio-samples/issues/189#issuecomment-556125233), the glitching problem is not the demo's fault. Please report your platform information via [crbug.com](https://bugs.chromium.org/p/chromium/issues/detail?id=1006844).

**Comment by hoch** [comment]
This issue is being fixed on https://crbug.com/1090441 starting from Pixel devices. Please follow the progress there.
