### ISSUE TITLE
Timer in AudioWorkletProcessor, SharedArrayBuffer, and the ring buffer design

### ISSUE THREAD

**Issue by JSmithOner** [GoogleChromeLabs/web-audio-samples#310]
I see you've added a  `waitTimeout` variable that is unused in the `SharedArrayBuffer` example.
I would like to implement some sort of 5 or 10 ms caching buffer timeout before pulling the data to the `outputDataChannel` of the worklet processor. 
Any ideas how I could achieve that the proper way.
Many thanks in advance.

**Comment by hoch** [comment]
AudioWorkletProcessor's callback always gives 128 sample-frames. So you'd have to create an array to accumulate the value. (of course you can count the number of samples too).

Implementing a timer within AudioWorkletProcessor is rather trivial. See this example:
https://github.com/GoogleChromeLabs/web-audio-samples/blob/main/src/audio-worklet/basic/message-port/messenger-processor.js

Once you have a timer, then you can add an event mechanism with MessagePort too.

**Comment by JSmithOner** [comment]
Thank you for you answer.After making a couple of research I'd rather implement an adaptive jitter. do you have any implementation examples.Thank for your time.

**Comment by hoch** [comment]
Adaptive jitter buffer is technically a ring buffer with the adaptation logic. Right? Then you can start from a ring buffer example. We recently published an example that uses a ring buffer (FreeQueue) for WebGPU integration:
https://github.com/GoogleChromeLabs/web-audio-samples/tree/main/src/experiments/webgpuaudio

**Comment by JSmithOner** [comment]
I'll take a look at that.Thank you very much.

**Comment by JSmithOner** [comment]
Also an another question I've been looking at the shared array buffer example and was wondering why the process is separated in a kernel and ringbuffer why is the data needs to be processed in a kernel and why not just into the output ring buffer? (I guess the kernel length is most of them time smaller than the ring buffer )?

**Comment by hoch** [comment]
Sorry for the late response!

I am not sure if I understand your question correctly. Feel free to follow up if I get it wrong.

The kernel is a component that can have an arbitrary block size. The Web Audio API renderer process the stream by 128 sample-frames ("render quantum") so if you have a different size of a kernel for custom audio code it won't work. That's why the SharedArrayBuffer example was introduced by detaching the kernel from the Web Audio API renderer's main render loop.

This limitation is from the specification and the spec maintainers are planning to remove it in the future.

**Comment by hoch** [comment]
Since the topic of this thread has changed a lot, so I am going to close this one. Please create a new issue if you have a different question!
